// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UFF.Monopoly.Data;

#nullable disable

namespace UFF.Monopoly.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251029214541_AddCompanyFieldsToBlockTemplate")]
    partial class AddCompanyFieldsToBlockTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.BlockStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("HotelPrice")
                        .HasColumnType("integer");

                    b.Property<int>("Hotels")
                        .HasColumnType("integer");

                    b.Property<int>("HousePrice")
                        .HasColumnType("integer");

                    b.Property<int>("Houses")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMortgaged")
                        .HasColumnType("boolean");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Rent")
                        .HasColumnType("integer");

                    b.Property<string>("RentsCsv")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameStateId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.BlockTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HotelPrice")
                        .HasColumnType("integer");

                    b.Property<int>("HousePrice")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Rent")
                        .HasColumnType("integer");

                    b.Property<string>("RentsCsv")
                        .HasColumnType("text");

                    b.Property<string>("Slogan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardDefinitionId", "Position")
                        .IsUnique();

                    b.ToTable("BlockTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#d4af37",
                            CompanyId = 0,
                            Description = "Leblon (Muito Rica)",
                            HotelPrice = 2000,
                            HousePrice = 1000,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 3,
                            LogoUrl = "",
                            Name = "Leblon",
                            Position = 0,
                            Price = 10000,
                            Rent = 100,
                            RentsCsv = "100,500,1000,1800,2200,2400,2500",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#d4af37",
                            CompanyId = 0,
                            Description = "Ipanema (Muito Rica)",
                            HotelPrice = 1840,
                            HousePrice = 920,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 3,
                            LogoUrl = "",
                            Name = "Ipanema",
                            Position = 1,
                            Price = 9200,
                            Rent = 92,
                            RentsCsv = "92,460,920,1656,2024,2208,2300",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#d4af37",
                            CompanyId = 0,
                            Description = "Jardim Botânico (Muito Rica)",
                            HotelPrice = 1760,
                            HousePrice = 880,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 3,
                            LogoUrl = "",
                            Name = "Jardim Botânico",
                            Position = 2,
                            Price = 8800,
                            Rent = 88,
                            RentsCsv = "88,440,880,1584,1936,2112,2200",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#d4af37",
                            CompanyId = 0,
                            Description = "São Conrado (Muito Rica)",
                            HotelPrice = 1680,
                            HousePrice = 840,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 3,
                            LogoUrl = "",
                            Name = "São Conrado",
                            Position = 3,
                            Price = 8400,
                            Rent = 84,
                            RentsCsv = "84,420,840,1512,1848,2016,2100",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#d4af37",
                            CompanyId = 0,
                            Description = "Lagoa (Muito Rica)",
                            HotelPrice = 1600,
                            HousePrice = 800,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 3,
                            LogoUrl = "",
                            Name = "Lagoa",
                            Position = 4,
                            Price = 8000,
                            Rent = 80,
                            RentsCsv = "80,400,800,1440,1760,1920,2000",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#3498db",
                            CompanyId = 0,
                            Description = "Copacabana (Rica)",
                            HotelPrice = 1400,
                            HousePrice = 700,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 2,
                            LogoUrl = "",
                            Name = "Copacabana",
                            Position = 5,
                            Price = 7000,
                            Rent = 70,
                            RentsCsv = "70,350,700,1260,1540,1680,1750",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#3498db",
                            CompanyId = 0,
                            Description = "Flamengo (Rica)",
                            HotelPrice = 1300,
                            HousePrice = 650,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 2,
                            LogoUrl = "",
                            Name = "Flamengo",
                            Position = 6,
                            Price = 6500,
                            Rent = 65,
                            RentsCsv = "65,325,650,1170,1430,1560,1625",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000108"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#3498db",
                            CompanyId = 0,
                            Description = "Botafogo (Rica)",
                            HotelPrice = 1200,
                            HousePrice = 600,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 2,
                            LogoUrl = "",
                            Name = "Botafogo",
                            Position = 7,
                            Price = 6000,
                            Rent = 60,
                            RentsCsv = "60,300,600,1080,1320,1440,1500",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000109"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#3498db",
                            CompanyId = 0,
                            Description = "Gávea (Rica)",
                            HotelPrice = 1100,
                            HousePrice = 550,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 2,
                            LogoUrl = "",
                            Name = "Gávea",
                            Position = 8,
                            Price = 5500,
                            Rent = 55,
                            RentsCsv = "55,275,550,990,1210,1320,1375",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000110"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#3498db",
                            CompanyId = 0,
                            Description = "Laranjeiras (Rica)",
                            HotelPrice = 1000,
                            HousePrice = 500,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 2,
                            LogoUrl = "",
                            Name = "Laranjeiras",
                            Position = 9,
                            Price = 5000,
                            Rent = 50,
                            RentsCsv = "50,250,500,900,1100,1200,1250",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000111"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#27ae60",
                            CompanyId = 0,
                            Description = "Humaitá (Mediana)",
                            HotelPrice = 700,
                            HousePrice = 350,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 1,
                            LogoUrl = "",
                            Name = "Humaitá",
                            Position = 10,
                            Price = 3500,
                            Rent = 35,
                            RentsCsv = "35,175,350,630,770,840,875",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000112"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#27ae60",
                            CompanyId = 0,
                            Description = "Leme (Mediana)",
                            HotelPrice = 640,
                            HousePrice = 320,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 1,
                            LogoUrl = "",
                            Name = "Leme",
                            Position = 11,
                            Price = 3200,
                            Rent = 32,
                            RentsCsv = "32,160,320,576,704,768,800",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000113"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#27ae60",
                            CompanyId = 0,
                            Description = "Maracanã (Mediana)",
                            HotelPrice = 600,
                            HousePrice = 300,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 1,
                            LogoUrl = "",
                            Name = "Maracanã",
                            Position = 12,
                            Price = 3000,
                            Rent = 30,
                            RentsCsv = "30,150,300,540,660,720,750",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000114"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#27ae60",
                            CompanyId = 0,
                            Description = "Tijuca (Mediana)",
                            HotelPrice = 560,
                            HousePrice = 280,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 1,
                            LogoUrl = "",
                            Name = "Tijuca",
                            Position = 13,
                            Price = 2800,
                            Rent = 28,
                            RentsCsv = "28,140,280,504,616,672,700",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000115"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#27ae60",
                            CompanyId = 0,
                            Description = "Andaraí (Mediana)",
                            HotelPrice = 500,
                            HousePrice = 250,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 1,
                            LogoUrl = "",
                            Name = "Andaraí",
                            Position = 14,
                            Price = 2500,
                            Rent = 25,
                            RentsCsv = "25,125,250,450,550,600,625",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000116"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#8b4513",
                            CompanyId = 0,
                            Description = "Madureira (Barata)",
                            HotelPrice = 240,
                            HousePrice = 120,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 0,
                            LogoUrl = "",
                            Name = "Madureira",
                            Position = 15,
                            Price = 1200,
                            Rent = 12,
                            RentsCsv = "12,60,120,216,264,288,300",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000117"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#8b4513",
                            CompanyId = 0,
                            Description = "Bonsucesso (Barata)",
                            HotelPrice = 200,
                            HousePrice = 100,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 0,
                            LogoUrl = "",
                            Name = "Bonsucesso",
                            Position = 16,
                            Price = 1000,
                            Rent = 10,
                            RentsCsv = "10,50,100,180,220,240,250",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000118"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#8b4513",
                            CompanyId = 0,
                            Description = "Campo Grande (Barata)",
                            HotelPrice = 180,
                            HousePrice = 90,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 0,
                            LogoUrl = "",
                            Name = "Campo Grande",
                            Position = 17,
                            Price = 900,
                            Rent = 9,
                            RentsCsv = "9,45,90,162,198,216,225",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000119"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#8b4513",
                            CompanyId = 0,
                            Description = "Realengo (Barata)",
                            HotelPrice = 160,
                            HousePrice = 80,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 0,
                            LogoUrl = "",
                            Name = "Realengo",
                            Position = 18,
                            Price = 800,
                            Rent = 8,
                            RentsCsv = "8,40,80,144,176,192,200",
                            Slogan = "",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000120"),
                            BoardDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#8b4513",
                            CompanyId = 0,
                            Description = "Paciência (Barata)",
                            HotelPrice = 120,
                            HousePrice = 60,
                            ImageUrl = "/images/blocks/property_basic.svg",
                            Level = 0,
                            LogoUrl = "",
                            Name = "Paciência",
                            Position = 19,
                            Price = 600,
                            Rent = 6,
                            RentsCsv = "6,30,60,108,132,144,150",
                            Slogan = "",
                            Type = 1
                        });
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.BoardDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CellSizePx")
                        .HasColumnType("integer");

                    b.Property<int>("Cols")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CellSizePx = 64,
                            Cols = 5,
                            CreatedAt = new DateTime(2025, 10, 27, 18, 30, 24, 0, DateTimeKind.Utc),
                            Name = "Rio Sample Board",
                            Rows = 5
                        });
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.GameStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.PlayerStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentPosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameStateId")
                        .HasColumnType("uuid");

                    b.Property<int>("GetOutOfJailFreeCards")
                        .HasColumnType("integer");

                    b.Property<bool>("InJail")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBankrupt")
                        .HasColumnType("boolean");

                    b.Property<int>("JailTurns")
                        .HasColumnType("integer");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PawnIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameStateId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("LastBoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("PawnImageUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.BlockStateEntity", b =>
                {
                    b.HasOne("UFF.Monopoly.Data.Entities.GameStateEntity", "Game")
                        .WithMany("Board")
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.BlockTemplateEntity", b =>
                {
                    b.HasOne("UFF.Monopoly.Data.Entities.BoardDefinitionEntity", null)
                        .WithMany("Blocks")
                        .HasForeignKey("BoardDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.PlayerStateEntity", b =>
                {
                    b.HasOne("UFF.Monopoly.Data.Entities.GameStateEntity", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.BoardDefinitionEntity", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("UFF.Monopoly.Data.Entities.GameStateEntity", b =>
                {
                    b.Navigation("Board");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
